### ISSUE TITLE
(LDA)How to set up scale related parameters?

### ISSUE THREAD

**Issue by ylqfp** [cloudml/zen#48]
Hi, I'm testing LDA for large scale dataset, billion docs*million words. However, spark originated lda always HANG, then i found ZEN.
However, I've not found parameter setup guide for lda, except simple description in source code.
My question is: 
1. There are several parameters relate to SCALE, is there a guide for setting them up?
2. As for parition number, how to choose for better parallelization?
Thanks!

**Comment by witgo** [comment]
ping @bhoppi

**Comment by bhoppi** [comment]
I think parameters relate to scale are -numPartitions and -numThreads. There is no general best strategy for all corpus, so you need to try.
But there are some principles to set these paras: for partitions number: setting it as less as possible, but to insure that blocks must be smaller than 2GB; for threads number: setting it appropriately, not to large or too small.
@hucheng Can you share the slides used for Kaiyuanshe about how to set up ZenLDA parameters? I don't have it.

**Comment by hucheng** [comment]
1. Prepare Zen Jar:
![image](https://cloud.githubusercontent.com/assets/308248/15006081/6e4d9b28-11ff-11e6-86cc-1776d1bf1f5c.png)
2. Spark-submit commands:
![image](https://cloud.githubusercontent.com/assets/308248/15006088/88f8bb10-11ff-11e6-81a0-f7e440134cf6.png)
3. Commands arguments:
![image](https://cloud.githubusercontent.com/assets/308248/15006098/96ea80be-11ff-11e6-85e6-749f2ff3210f.png)
4. Tips on LDA usage:
![image](https://cloud.githubusercontent.com/assets/308248/15006107/aeb75d48-11ff-11e6-9b7a-6d642fa59ed8.png)

**Comment by ylqfp** [comment]
Thanks So Much!!! Closed. @hucheng
