### ISSUE TITLE
mvn package fail

### ISSUE THREAD

**Issue by ylqfp** [cloudml/zen#49]
Hi, I checked out the newest master branch, and mvn package, finally got some errors.

Downloaded: https://repo.maven.apache.org/maven2/org/scala-lang/scala-compiler/2.10.6/scala-compiler-2.10.6.jar (14134 KB at 127.9 KB/sec)
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-versions) @ zen-ml_2.10 ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ zen-ml_2.10 ---
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:add-source (eclipse-add-source) @ zen-ml_2.10 ---
[INFO] Add Source directory: /search/odin/yulei/spark_models/zen/ml/src/main/scala
[INFO] Add Test Source directory: /search/odin/yulei/spark_models/zen/ml/src/test/scala
[INFO] 
[INFO] --- build-helper-maven-plugin:1.7:add-source (add-scala-sources) @ zen-ml_2.10 ---
[INFO] Source directory: /search/odin/yulei/spark_models/zen/ml/src/main/scala added.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ zen-ml_2.10 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /search/odin/yulei/spark_models/zen/ml/src/main/resources
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:compile (scala-compile-first) @ zen-ml_2.10 ---
[WARNING] Zinc server is not available at port 3030 - reverting to normal incremental compile
[INFO] Using incremental compilation
[INFO] 'compiler-interface' not yet compiled for Scala 2.10.6. Compiling...
[INFO]   Compilation completed in 19.924 s
[INFO] compiler plugin: BasicArtifact(org.scalamacros,paradise_2.10.6,2.0.1,null)
Downloading: https://repo.maven.apache.org/maven2/org/scalamacros/paradise_2.10.6/2.0.1/paradise_2.10.6-2.0.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/scalamacros/paradise_2.10.6/2.0.1/paradise_2.10.6-2.0.1.jar (1807 KB at 107.2 KB/sec)
[INFO] Compiling 98 Scala sources and 4 Java sources to /search/odin/yulei/spark_models/zen/ml/target/scala-2.10/classes...
[WARNING] /search/odin/yulei/spark_models/zen/ml/src/main/scala/com/github/cloudml/zen/ml/recommendation/BSFMModel.scala:117: non-variable type argument Double in type pattern Seq[Double] is unchecked since it is eliminated by erasure
[WARNING]         case Row(featureId: Long, factors: Seq[Double]) =>
[WARNING]                                            ^
[WARNING] /search/odin/yulei/spark_models/zen/ml/src/main/scala/com/github/cloudml/zen/ml/recommendation/FMModel.scala:112: non-variable type argument Double in type pattern Seq[Double] is unchecked since it is eliminated by erasure
[WARNING]         case Row(featureId: Long, factors: Seq[Double]) =>
[WARNING]                                            ^
[WARNING] /search/odin/yulei/spark_models/zen/ml/src/main/scala/com/github/cloudml/zen/ml/recommendation/MVMModel.scala:115: non-variable type argument Double in type pattern Seq[Double] is unchecked since it is eliminated by erasure
[WARNING]         case Row(featureId: Long, factors: Seq[Double]) =>
[WARNING]                                            ^
[WARNING] /search/odin/yulei/spark_models/zen/ml/src/main/scala/com/github/cloudml/zen/ml/tree/Node.scala:20: imported `Node' is permanently hidden by definition of object Node in package tree
[WARNING] import org.apache.spark.mllib.tree.model.{Node, Predict}
[WARNING]                                           ^
[WARNING] four warnings found
[WARNING] warning: [options] bootstrap class path not set in conjunction with -source 1.6
[WARNING] 1 warning
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ zen-ml_2.10 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 4 source files to /search/odin/yulei/spark_models/zen/ml/target/scala-2.10/classes
[INFO] 
[INFO] --- build-helper-maven-plugin:1.7:add-test-source (add-scala-test-sources) @ zen-ml_2.10 ---
[INFO] Test Source directory: /search/odin/yulei/spark_models/zen/ml/src/test/scala added.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ zen-ml_2.10 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:testCompile (scala-test-compile-first) @ zen-ml_2.10 ---
[WARNING] Zinc server is not available at port 3030 - reverting to normal incremental compile
[INFO] Using incremental compilation
[INFO] compiler plugin: BasicArtifact(org.scalamacros,paradise_2.10.6,2.0.1,null)
[INFO] Compiling 12 Scala sources to /search/odin/yulei/spark_models/zen/ml/target/scala-2.10/test-classes...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Zen Project Parent POM ............................. SUCCESS [  2.416 s]
[INFO] Zen Project ML Library ............................. FAILURE [03:58 min]
[INFO] Zen Project Assembly ............................... SKIPPED
[INFO] Zen Project Examples ............................... SKIPPED

**Comment by ylqfp** [comment]
-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ zen-ml_2.10 ---
Discovery starting.
Discovery completed in 1 second, 181 milliseconds.
Run starting. Expected test count is: 9
MLPSuite:
- MLP !!! IGNORED !!!
- binary classification !!! IGNORED !!!
FMSuite:
14.726
0.2809007218328279
0.6851166440004188
0.8729145308086648
0.8941385082121622
0.898689193430282
0.9027942253373826
0.9042399832618528
0.907098022805737
0.9080709279213355
0.9100899675698327
An exception or error caused a run to abort. This may have been caused by a problematic custom reporter.
Exception in thread "ScalaTest-main" Exception in thread "SparkListenerBus" 
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "ScalaTest-main"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "SparkListenerBus"

**Comment by ylqfp** [comment]
@witgo

**Comment by witgo** [comment]
Try the following command.
 `mvn -DskipTests clean  package`

**Comment by ylqfp** [comment]
Thanks! Problem cleared.
